services:
  grin-platform:
    image: hcley/grin-platform:latest
    container_name: "${GRIN_PLATFORM:-grin-platform}"
    ports:
      - "4200:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.grin.loadbalancer.server.port=4200"
      - "traefik.http.services.grin.loadbalancer.server.scheme=http"
      - "traefik.http.routers.grin.rule=Host(`grin.logiclabsoftwares.com`)"
      - "traefik.http.routers.grin.entrypoints=https"
      - "traefik.http.routers.grin.tls.certresolver=cloudflare"
      - "traefik.http.routers.grin.middlewares=traefik-auth"
      - "traefik.http.routers.grin.service=grin"
    networks:
      proxy:
    security_opt:
      - no-new-privileges:true

networks:
  proxy:
    external: true
