services:
  grin-platform:
    container_name: "${GRIN_PLATFORM:-grin-platform}"
    image: hcley/grin-platform:latest
    pull_policy: always
    ports:
      - "4001:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.grin.loadbalancer.server.port=80"
      # - "traefik.http.routers.grin.entrypoints=http"
      - "traefik.http.routers.grin.entrypoints=https"
      - "traefik.http.routers.grin.rule=Host(`grin.logiclabsoftwares.com`)"
      - "traefik.http.routers.grin.tls.certresolver=cloudflare"
      - "traefik.http.routers.grin-secure.tls=true"
      - "traefik.http.routers.grin.middlewares=traefik-auth,jellyfin-https-redirect"
      - "traefik.http.routers.grin.service=grin"
