services:
  db:
    container_name: PlatformDB
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: "platform"
    volumes:
      - grindb:/var/lib/postgresql/data
    ports:
      - "5050:5432"

volumes:
  grindb:
