# .github/actions/add-server-key/action.yml
name: "Add Server Public Key"
description: "Reusable step to add server public key"

inputs:
  key_export_name:
    required: false
    default: "./cloud.key"
    description: "Key file name (including path, such as './') and file extension (file.key / file.pem)"
  CLOUD_RSA_KEY:
    description: "Cloud RSA key file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Add server public key
      shell: bash
      run: |
        echo "${{ inputs.CLOUD_RSA_KEY }}" > $key_file
        chmod 600 $key_file
