# .github/actions/cloud-ssh/action.yml
name: "Stop and remove docker container"
description: "Reusable step to stop and remove a docker container"

inputs:
  key_file:
    required: false
    default: "./cloud.key"
    description: "Key file name (including path, such as './') and file extension (file.key / file.pem)"
  CLOUD_USER:
    required: true
    description: "Cloud user with access granted to the RSA key file"
  CLOUD_ADDRESS:
    required: true
    description: "Cloud address host (able to accept ssh) being IPv4 or DNS."

runs:
  using: "composite"
  steps:
    - name: Inject compose file to server
      shell: bash
      run: |
        ssh -t -o StrictHostKeyChecking=no -i "${{ inputs.key_file }}" ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_ADDRESS }} << EOF
        EOF

