name: API CI

on:
  push:
    branches: ["release"]
    paths:
      - "spring/**"
      - "!spring/docs/**"
  pull_request:
    branches: ["release"]
    types: ["approved"]
    paths:
      - "spring/**"
      - "!spring/docs/**"

env:
  REGISTRY_IMAGE: ${{ vars.REGISTRY }}/${{ vars.PLATFORM_IMAGE_NAME }}

jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Test workflow event
        run: echo "called"
