name: AGENT CI-CD

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main
      - release
    paths:
      - ".github/workflows/agent-pipeline.yml"
      - "agent/**"

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          INSTALL_FLAGS="--break-system-packages --force-reinstall"
          pip install agent/. $INSTALL_FLAGS

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |

            agent/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
