name: AGENT CI-CD

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
    branches:
      - main
      - release
    paths:
      - ".github/workflows/agent-pipeline.yml"
      - "agent/**"

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.2"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build

      - name: Build
        run: |
          INSTALL_FLAGS="--break-system-packages --force-reinstall"
          pip install agent/. $INSTALL_FLAGS

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |

            agent/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
