name: Database CI-CD

on:
  schedule:
    - cron: "0 0 * * 0" # This runs every Sunday at midnight UTC

env:
  key_file: ./cloud.key

jobs:
  database:
    uses: ./.github/workflows/backup.yml
    with:
      backup: dump
      SERVICE_NAME: ${{ vars.API_SERVICE_NAME }}
      CONTAINER_NAME: ${{ vars.API_CONTAINER_NAME }}
    secrets:
      ENV_FILE: ${{ secrets.DB_ENV_FILE }}
      BUCKET_TOKEN: ${{ secrets.BUCKET_TOKEN }}
      CLOUD_USER: ${{ secrets.CLOUD_USER }}
      CLOUD_ADDRESS: ${{ secrets.CLOUD_ADDRESS }}
      CLOUD_RSA_KEY: ${{ secrets.CLOUD_RSA_KEY }}
