name: Build docker image as artifact

on:
  workflow_dispatch:
    inputs:
      status:
        required: true
        default: "deployed"
        description: "If value set to observe, the double-check stage will not be triggered again."

  workflow_call:
    inputs:
      key_file:
        type: string
        required: false
        default: "./cloud.key"
        description: "Key file name (including path, such as './') and file extension (file.key / file.pem)"
      CONTAINER_NAME:
        type: string
        required: true
        description: "Desired name to be set at containar that is being deployed"

    secrets:
      CLOUD_RSA_KEY:
        required: true
        description: "Username able to login into image registry account"
      CLOUD_USER:
        required: true
        description: "Password able to login into image registry account"
      CLOUD_ADDRESS:
        required: true
        description: "Cloud address host (able to accept ssh) being IPv4 or DNS."

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add server public key
        uses: ./.github/actions/cloud-keys
        with:
          CLOUD_RSA_KEY: ${{ secrets.CLOUD_RSA_KEY }}

      - name: Inject compose file to server
        uses: ./.github/actions/cloud-scp
        with:
          local_path: ./api/docker-compose.yml
          target_path: /home/${{ secrets.CLOUD_USER }}
          CLOUD_USER: ${{ secrets.CLOUD_USER }}
          CLOUD_ADDRESS: ${{ secrets.CLOUD_ADDRESS }}

      - name: Validate container existance
        id: healthcheck
        run: |
          ssh -t -o StrictHostKeyChecking=no -i "${{ inputs.key_file }}" ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_ADDRESS }} << EOF
            sudo -i

            if docker ps --filter "name=${{ inputs.CONTAINER_NAME }}" --format "{{.Names}}" | grep -w "${{ inputs.CONTAINER_NAME }}"; then
              echo "${GREEN}${{ inputs.CONTAINER_NAME }} is currently running.${CLEAR}"
              echo "status=healthy" >> $GITHUB_OUTPUT
              exit 0;
            else
              echo -e "${RED}${{ inputs.CONTAINER_NAME }} is not running or not healthy.${CLEAR}"
              echo "status=unhealthy" >> $GITHUB_OUTPUT
              exit 1;
            fi
          EOF

      - name: Wait for potential database success
        id: double-check
        if: always() && ${{ github.event.inputs.status != 'deployed' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TIMEOUT: 360 # 6 MINUTES
        run: |
          echo "Dispatch event: ${{ github.event.inputs.status }}"
          echo "Waiting for database deploy job to complete..."
          start_time=$(date +%s)
          while true; do
            current_time=$(date +%s)
            elapsed=$(( current_time - start_time ))

            if [[ $elapsed -ge ${{ env.TIMEOUT }} ]]; then
                echo -e "\033[31mTimeout waiting for database deploy job to complete.\033[0m"
                exit 1
            fi

            job=$(gh run view ${{ github.run_id }} --json jobs | jq '.jobs[] | select(.name=="database / deploy")')
            job_status=$(echo "$job" | jq -r '.conclusion')
            deploy_job=$(echo "$job" | jq '.steps[] | select(.name=="Deploy")')
            deploy_job_status=$(echo "$deploy_job" | jq -r '.conclusion')

            if [[ "$job_status" == "cancelled" || "$job_status" == "failure" ]]; then
              echo "\033[33mPrevious status: ${{ toJson(steps.healthcheck.outputs.status) }}\033[0m"
              if [[ "$deploy_job_status" == "skipped" ]]; then
                exit 0
              fi
              exit 1
            fi

            if [[ "$deploy_job_status" == "success" ]]; then
              echo -e "\033[32mTrigger dispatch\033[0m"
              curl -X POST \
                -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
                -H "Accept: application/vnd.github+json" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.run_id }}/dispatches \
                -d '{"ref":"release", "inputs":{"task":"deployed"}}'
              exit 0
            fi

            sleep 10
          done
