name: Build docker image as artifact

on:
  workflow_call:
    inputs:
      key_file:
        type: string
        required: false
        default: "./cloud.key"
        description: "Key file name (including path, such as './') and file extension (file.key / file.pem)"
      CONTAINER_NAME:
        type: string
        required: true
        description: "Desired name to be set at containar that is being deployed"

    secrets:
      CLOUD_RSA_KEY:
        required: true
        description: "Username able to login into image registry account"
      CLOUD_USER:
        required: true
        description: "Password able to login into image registry account"
      CLOUD_ADDRESS:
        required: true
        description: "Cloud address host (able to accept ssh) being IPv4 or DNS."

jobs:
  observe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add server public key
        uses: ./.github/actions/cloud-keys
        with:
          CLOUD_RSA_KEY: ${{ secrets.CLOUD_RSA_KEY }}

      - name: Inject compose file to server
        uses: ./.github/actions/cloud-scp
        with:
          local_path: ./api/docker-compose.yml
          target_path: /home/${{ secrets.CLOUD_USER }}
          CLOUD_USER: ${{ secrets.CLOUD_USER }}
          CLOUD_ADDRESS: ${{ secrets.CLOUD_ADDRESS }}

      - name: Validate container existance
        run: |
          ssh -t -o StrictHostKeyChecking=no -i "${{ inputs.key_file }}" ${{ secrets.CLOUD_USER }}@${{ secrets.CLOUD_ADDRESS }} << EOF
            sudo -i

            if docker ps --filter "name=${{ inputs.CONTAINER_NAME }}" --format "{{.Names}}" | grep -w "${{ inputs.CONTAINER_NAME }}"; then
              echo "${GREEN}${{ inputs.CONTAINER_NAME }} is currently running.${CLEAR}"
              exit 0;
            else
              echo -e "${RED}${{ inputs.CONTAINER_NAME }} is not running or not healthy.${CLEAR}"
              exit 1;
            fi
          EOF

      - name: Wait for potential database success
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Waiting for database job to complete..."
          while true; do
            job=$(gh run view ${{ github.run_id }} --json jobs | jq '.jobs[] | select(.name=="database / deploy")')
            job_status=$(echo "$job" | jq '.conclusion')
            deploy_job=$(echo "$job" | jq '.steps[] | select(.name=="Deploy")')

            echo "$job_status"
            echo "$deploy_job"
            echo "------"

            if [[ "$job_status" != "null" ]]; then
              break
            fi
            sleep 10
          done

      # - name: Re-run health check if database succeeds
      #   if: ${{ inputs.DATABASE_RESULT == 'success' }}
      #   run: echo "Re-running health check after database success!"
